apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argo-workflows
      targetRevision: 0.47.3
      helm:
        valueFiles:
          - $values/apps/data/argo_workflow/values.yaml
    - repoURL: 'https://github.com/gouv-nc-data/gke_gitops'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Nécessaire pour les gros CRDs Argo Workflows
